version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./downloads:/app/downloads
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
    # Especifica la plataforma si se tiene problemas de compatibilidad
    platform: linux/amd64  # Opcional para compatibilidad